secultce/theme-Ceara

- .idea/workspace.xml
- image-transformations.php
- layouts/parts/singles/avatar.php
Alterando tamanho da imagem do tipo avatar BIG utilizado nos eventos para 720x720
> Alterando tamanho da imagem do tipo avatar BIG utilizado nos eventos para 720x720

- views/opportunity/report-old.php
correcao do relatorio  inscritos antigo
> correcao do relatorio  inscritos antigo

- views/opportunity/report-old.php
bug do botão antigo do relatório 2215 corrigido
> bug do botão antigo do relatório 2215 corrigido

- Theme.php
- layouts/parts/bank-defails-edit--form.php
- layouts/parts/reason-failure.php
adiciona formulario de atualizar dados bancarios e motivo de reprovação
> adiciona formulario de atualizar dados bancarios e motivo de reprovação

- views/opportunity/report-old.php
Bug do relatório botao antigo corrigido
> Bug do relatório botao antigo corrigido

- Theme.php
- assets/js/opportunity-ceara/hidebutton.js
- assets/js/scroll.js
- layouts/parts/gallery.php
- layouts/parts/nav-main-user.php
- layouts/parts/opportunity/opportunity_modal_ceara.php
Mesclando modalProjeto com develop.
> Modal projeto

- Theme.php
- assets/js/scroll.js
- layouts/parts/gallery.php
Ajustes de paginação com scroll e mudança de itens por página para 100
> Improvements pagination

- Theme.php
- layouts/parts/site/header.php
Colocado botão do chat junto ao menu com um redirecionamento
> :wheelchair: Alterando posição do botão do chat

- README.md
- Theme.php
✅ Alterado Readme
✅ Removido código duplicado
> Merge Develop to Master

- assets/css/sass/_overrides.scss
Add outras configurações de estilo para melhor experiencia dos avaliadores
> :lipstick: Ajusta classe para avaliador

- Theme.php
- views/panel/index.php
1. Ajustado layout para avaliador
2. Tratamento de erro para inscrição excluída
> Merge To Develop

- Theme.php
♿ Adicionado em outras rotas o hook que inclui o botão de suporte.
> :wheelchair: Add outros hook para botão de suporte

- views/panel/index.php
> :bricks: Incluido conf de memoria

- Theme.php
- views/panel/index.php
:bug: Removido hook para inscrição excluida
> :bug: Removido hook para inscrição excluida

- Controllers/Registration.php
Para algumas oportunidades com o campo de anexo, o usuário não consegue fazer o upload de arquivo, foi contatado que há um problema de formatação de UTF8 com o titulo que é descrito do arquivo.
Alterado a função `preg_replace` que remove os espaços da string do titulo do campo para upload no arquivo Registration.php
> :children_crossing: Alterado replace para titulo do campo

- Controllers/Registration.php
Para algumas oportunidades com o campo de anexo, o usuário não consegue fazer o upload de arquivo, foi contatado que há um problema de formatação de UTF8 com o titulo que é descrito do arquivo.
Alterado a função `preg_replace` que remove os espaços da string do titulo do campo para upload no arquivo Registration.php
> 🔀 Merge Develop to Master

- Controllers/SearchAll.php
- Theme.php
- assets/css/search/style.css
- assets/css/tabs/style.css
- assets/js/agents/search/ng.agent-search.js
- views/pesquisar/index.php
No painel administrativo nao tem como pesquisar por E-mail do agente e outras opções
Criado uma página para realização dessa pesquisa.
> 🔀 Feature/search email

- assets/css/main.css
- assets/css/sass/_overrides.scss
Corrigido comportamento da barra lateral, para somente na aba de avaliações e para que contenha uma barra de rolagem.
> fix: Corrigido comportamento da sidebar

- Theme.php
- assets/js/opportunity-ceara/prevent-remove-evaluator.js
Adiconado aviso a na aba de configuração da avaliação.
> Adicionado aviso sobre exclusão de avaliadores

- ApiOutputs/Json.php
- Controllers/Opportunity.php
- Theme.php
- assets/js/hotjar.js
- assets/js/opportunity-ceara/btn-disable-on-register.js
Adiconado operador de encadeamento condicional (?.)
> fix: Correção do listener ao click do botão registrar inscrição

- layouts/parts/singles/opportunity-about--highlighted-message.php
> Limitar inscrições pelo número configurado no projeto

- CHANGELOG.md
- Theme.php
Removido botão apagar inscrição
---
Closes #122
---
---
---
---
---
> Removendo botão de apagar inscrição

- Theme.php
> Vagas para cotistas (registro de metadados na oportunidade)

- CHANGELOG.md
Atualizando changelog
---
---
---
---
---
> :memo: Adicionado changelog

- CHANGELOG.md
Atualizando main
---
---
---
---
---
> 🔁 Merge Develop to Main

- Theme.php
- assets/js/opportunity-ceara/prevent-remove-evaluator.js
- views/opportunity/report-csv.php
- views/opportunity/report-old.php
> Terminologia prestação de contas

- CHANGELOG.md
- Theme.php
- assets/js/opportunity-ceara/prevent-remove-evaluator.js
- views/opportunity/report-csv.php
- views/opportunity/report-old.php
> Develop to main

- views/panel/index.php
> Exibir no painel inicial somente inscrições/avaliações de oportunidades não prestação de contas

- Theme.php
Atualização da develop para master
---
---
---
---
---
> ✨ Merge develop to master

- Theme.php
- layouts/parts/opportunity/btn-publish-site.php
> Melhoria no posicionamento da seção do Site Editais
